## 몇 가지 Torch로 텐서를 생성하는 방법 입니다.

In [3]:
## torch load
import torch
import numpy as np
print(torch.__version__) # 토치 버전 확인
print(torch.cuda.is_available()) ## 그래픽 카드 사용가능 여부

1.10.0+cu111
True


### 0으로 이루어진 Tensor 생성 방법

In [5]:
z = torch.zeros(5,3)
print("생성된 Tonsor:\n",z)
print("데이터의 타입:",z.dtype)

생성된 Tonsor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
데이터의 타입: torch.float32


In [11]:
print("생성된 Tensor를 array로 바꾸기:")
print(np.array(z))
print()
print("타입 바꾸기:")
print(np.array(z, dtype=np.uint8))

생성된 Tensor를 array로 바꾸기:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

타입 바꾸기:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
# array를 Tensor로 바꾸기
torch.tensor(np.array(z))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 1으로 이루어진 Tensor 생성 방법

In [14]:
i = torch.ones((5,3), dtype = torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


- 랜덤하게 값을 뽑아도 seed 값을 설정하면 값은 값을 뽑을 수 있음.
  - 같은 값을 뽑으면 random이 아니 잖아요 .. ? 라고 질문 하시는 분이 계심
  - 랜덤이지만 같은 값을 뽑는 이유는 잘 학습된 모델에서 seed를 설정하지 않으면, 해당 모델의 성능 바뀔 가능성이 있기 때문에 최대한 seed 값을 설정해서 다른 누가 모델을 이용해 학습을 하더라도 같은 결과를 얻기 위한 방법입니다.

In [15]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print(r1)

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [16]:
r2 = torch.rand(2,2)
print("different random tensor:")
print(r2)

different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])


In [17]:
torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3)


Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


### Tensor 연산

In [18]:
ones = torch.ones(2,3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
twos = torch.ones(2,3) * 2
print(twos)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [20]:
threes = ones + twos
print(threes)
print(threes.shape)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


In [5]:
r = torch.rand(2,2) - 0.5 * 2
print("A random matrix, r :")
print(r)

A random matrix, r :
tensor([[-0.2930, -0.1680],
        [-0.9514, -0.9217]])


In [6]:
## 절대 값
print("\nAbsolute value of r:")
print(torch.abs(r)) # 절대 값

## 삼각법
print("\nInverse sine of r:")
print(torch.asin(r)) # arcsin 적용

## 행렬식과 특잇값 분해
print("\nDeterminant of r:")
print(torch.det(r)) # 역행력 곱

print("\nSingular value decomposition of r:")
print(torch.svd(r))

# 표준 편차와 최대 값:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))


Absolute value of r:
tensor([[0.2930, 0.1680],
        [0.9514, 0.9217]])

Inverse sine of r:
tensor([[-0.2974, -0.1688],
        [-1.2576, -1.1724]])

Determinant of r:
tensor(0.1102)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.2408, -0.9706],
        [-0.9706,  0.2408]]),
S=tensor([1.3646, 0.0808]),
V=tensor([[ 0.7284,  0.6852],
        [ 0.6852, -0.7284]]))

Average and standard deviation of r:
(tensor(0.4110), tensor(-0.5835))

Maximum value of r:
tensor(-0.1680)


![nn](https://miro.medium.com/max/1200/1*-ycNEMicMOIR8WvzcBzERA@2x.jpeg)

In [7]:
## 행력식 예시
r_arr = np.array(r)
print(r_arr)

np.round((abs(r_arr[0][0]) * abs(r_arr[1][1])) - (abs(r_arr[0][1]) * abs(r_arr[1][0])), 4)

[[-0.29302502 -0.1680187 ]
 [-0.9513594  -0.92169946]]


0.1102

평균 및 분산, 표준편차

In [8]:
## r tensor를 array로 변경
r_arr = np.array(r)
print(r_arr)

[[-0.29302502 -0.1680187 ]
 [-0.9513594  -0.92169946]]


In [14]:
## 평균
ag = (r_arr[0][0] + r_arr[0][1] + r_arr[1][0] + r_arr[1][1]) / 4
n = 4
print("r tensor의 평균:", np.round(ag, 4))

## 분산
var = r_arr - ag
var = pow(var, 2)
var = var[0][0] + var[0][1] + var[1][0] + var[1][1]
var = (var / (n - 1))
print("r tensor의 분산: ", np.round(var, 4))

## 표준 편차
std = np.sqrt(var)
print("r tensor의 표준 편차:", np.round(std, 4))

## 최댓 값
print("r array의 최댓 값:",r_arr.max())

r tensor의 평균: -0.5835
r tensor의 분산:  0.1689
r tensor의 표준 편차: 0.411
r array의 최댓 값: -0.1680187
